# Generated by Django 3.2.6 on 2021-09-02 02:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='canPause',
            new_name='guestCanPause',
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.createCode, max_length=8, unique=True),
        ),
    ]
