# Generated by Django 3.2.6 on 2021-09-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210902_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='currentSong',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
